# Generated by Django 2.2.19 on 2022-08-11 14:41

import TOTO_TOOLS.users.manager
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('username', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='username')),
                ('nickname', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='nickname')),
                ('region', models.CharField(choices=[('서울특별시', '서울특별시'), ('경기도', '경기도'), ('인천광역시', '인천광역시'), ('강원도', '강원도'), ('충청북도', '충청북도'), ('충청남도', '충청남도'), ('전라남도', '전라남도'), ('전라북도', '전라북도'), ('광주광역시', '광주광역시'), ('경상남도', '경상남도'), ('경상북도', '경상북도'), ('제주특별자치도', '제주특별자치도'), ('NONE', 'NONE')], default='NONE', max_length=300, null=True)),
                ('grade', models.CharField(choices=[('VISITOR', 'VISITOR'), ('DOCTORS', 'DOCTORS'), ('LEVEL1', 'LEVEL1'), ('ADMINSTRATOR', 'ADMINSTRATOR')], default='VISITOR', max_length=300, null=True)),
                ('sex', models.CharField(choices=[('NO_GENDER', 'NO_GENDER'), ('FEMALE', 'FEMALE'), ('MALE', 'MALE')], default='NO_GENDER', max_length=300, null=True, verbose_name='sex')),
                ('birthday', models.DateField(null=True)),
                ('school', models.CharField(choices=[('초등학교', '초등학교'), ('중학교', '중학교'), ('고등학교', '고등학교'), ('특수학교', '특수학교'), ('NONE', 'NONE')], default='NONE', max_length=300, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Contact Phone')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', TOTO_TOOLS.users.manager.CustomUserManager()),
            ],
        ),
    ]
